### ISSUE TITLE
stuck before beating viridian jackson

### ISSUE THREAD

**Issue by c0pper** [g0ldPRO/Questing.lua#1]
all the team is at least at lvl 8. After the last pokemon got to the designated level it got stuck in viridian city school underground on this dialog: 
[21:28:38] Sorry, the young boy there doesn't want to give his spot, I'm truly sorry...
[21:28:38] You should go on your road as a Pokemon trainer.

https://gyazo.com/c7828d8306ef201cc7403a40636046ba

**Comment by g0ldPRO** [comment]
Thank you for reporting it.
Fixed in commit [11e326db5a510d09c5c722c6fc65157a41694c1b](https://github.com/g0ldPRO/Questing.lua/commit/11e326db5a510d09c5c722c6fc65157a41694c1b)
