### ISSUE TITLE
Remove doduo from team

### ISSUE THREAD

**Issue by 0x526f6d656f** [g0ldPRO/Questing.lua#20]
Can you somehow auto-remove duduo from the team? Tested it on several accounts, and Duduo always takes the longest to train, making the bot train for a way longer timer than neccessary.

**Comment by Silv3rPRO** [comment]
Just add Doduo to the file `blacklist.lua`.

**Comment by g0ldPRO** [comment]
The blacklist has been disabled. I am working on a more advanced team selection system.  
Expect terrible teams until then. :D
