### ISSUE TITLE
Try to drink a potion on route 1

### ISSUE THREAD

**Issue by Silv3rPRO** [g0ldPRO/Questing.lua#5]
> Bot started
> Starting new quest: Viridian School: from Route 1 to Route 2
> System: The Server is currently full.HP

Route 1 with a full-health Squirtle.
Don't mind the error message, it looks weird because of a bug in PROShine.
The original message is `Your Pokemon already has full HP!`.

Probably comes from this piece of code:

``` lua
function ViridianSchoolQuest:Route1()
    if self:needPokecenter() then
        if useItemOnPokemon("Potion", 1) then
            return true
        end
    end
    return moveToMap("Route 1 Stop House")
end
```

**Comment by g0ldPRO** [comment]
Thank you.  
Fixed in commit 126c8da8f9a853a9d8ddb95d730e35436c83f55c
