### ISSUE TITLE
Mt Moon

### ISSUE THREAD

**Issue by irrefragable** [g0ldPRO/Questing.lua#7]
The bot just go in and out of the mt moon without doing anything after my pokemon got the right level. I tried many times.

**Comment by irrefragable** [comment]
I fixed it by going manually to the B2F and then restarting to use the script.

**Comment by irrefragable** [comment]
I fixed it by going manually to the B2F and then restarting to use the script.

**Comment by g0ldPRO** [comment]
I am currently adding the PC support to the PROShine API. After what I will release a new Questing.lua version including a fix for this bug.

**Comment by g0ldPRO** [comment]
Duplicate of #4
